services:

  db:
    image: postgres:14.5
    container_name: db-postgres
    build:
      context: .
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: globant_challenge
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/path/to/csv
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  webapp:
    image: python:3.11.5
    container_name: rest-api
    build:
      context: .
    environment:
      PIP_ROOT_USER_ACTION: ignore
    ports:
      - 8000:8000
    volumes:
      - ./requirements.txt:/src/requirements.txt
      - ./rest_api.py:/rest_api.py
    command: >
      sh -c "pip3 install --no-cache-dir --upgrade -r ./src/requirements.txt &&
             python3 -m uvicorn rest_api:app --host 0.0.0.0 --port 8000 --reload"
